### ISSUE TITLE
UI exception in Safari browser

### ISSUE THREAD

**Issue by hi-asan** [TeselaGen/tg-oss#37]
@tnrich
<img width="1676" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/12293038/e49ece68-27e3-45d6-ac3c-6502e7e222f2">
<img width="1429" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/12293038/60235d7d-e825-49bc-aac3-ab8c9463fd3b">

If you need any additional information, I can provide it

**Comment by hi-asan** [comment]
<img width="457" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/12293038/1363652c-4468-4281-bcc2-ae826e277d3a">
set letter-spacing:3px  Looks normal

**Comment by tnrich** [comment]
@hi-asan I'm not able to reproduce the row view issue you are seeing on safari, for me it looks fine: 

<img width="1512" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/2730609/2b0f31f7-4556-4d52-9613-c4da0c31f47c">

I do see the issue where the sequence name is not being drawn in the middle of the circular view. That is due to an issue with foreignObjects and absolute positioning in safari: https://stackoverflow.com/questions/8185845/svg-foreignobject-behaves-as-though-absolutely-positioned-in-webkit-browsers

I went ahead and tried to fix that using a flexbox approach that seems to work on safari (for me). Please try that and let me know if it fixed it for you. 

As for the row view issue, I'm not able to reproduce that currently. Please provide additional details and screenshots. We might need to pair to fix that one. 

Thanks!

**Comment by hi-asan** [comment]
We have identified the issue and have recently updated the system to the latest Sonama 14.0. The Safari browser inside has also been updated to 17.0. Your browser version is definitely lower than this version. I have tried it on several Mac computers, and all updates to the latest version have the same issue. That is, the issue of sequence character width

**Comment by hi-asan** [comment]
@tnrich

Thank you for your reply

We have identified the issue and have recently updated the system to the latest Sonama 14.0. The Safari browser inside has also been updated to 17.0. Your browser version is definitely lower than this version. I have tried it on several Mac computers, and all updates to the latest version have the same issue. That is, the issue of sequence character widt

**Comment by tnrich** [comment]
Thanks for looking further into this @hi-asan. I'll upgrade to sonoma and then push a fix for this when I have one :)

**Comment by tnrich** [comment]
@hi-asan thanks for following up. I've pushed a fix for this to the latest version of ove

**Comment by hi-asan** [comment]
> @hi-asan thanks for following up. I've pushed a fix for this to the latest version of ove. Let me know if that fixes it for you@hi-阿桑感谢您的跟进。我已经将此问题的修复程序推送到最新版本的 ove。让我知道这是否为您解决了

The problem has been solved, thank you very much
