### ISSUE TITLE
Issues with OVE

### ISSUE THREAD

**Issue by NicolasCARPi** [TeselaGen/tg-oss#79]
@tnrich

Hello,

In OVE 0.5 `react` and `react-dom` have been removed, which causes a build issue, as your app depends on it. Is there a reason for that removal, what are users expected to do? Shouldn't it be a peerDependency then?

Additionally, I find it challenging to track changes in this package. Including a CHANGELOG.md file in the package directory would be immensely helpful :pray: . Relying on the commit history is not ideal. The README.md also needs some updates, as it contains several broken links, such as the one to UPGRADE INSTRUCTIONS.

For example, I encountered an issue with CSS disappearing between versions 0.4.10 and 0.4.11. Without tags, releases, or a changelog, it's difficult to identify the cause. Could you provide any insights into changes between these versions that might have affected the CSS? I would typically review changes in 0.4.12 for mentions of CSS, but without clear versioning, this is challenging.

I understand the single repo approach has limitations, but a proper CHANGELOG for each package would greatly benefit downstream developers.

Lastly, I noticed that lodash-es is now in use, but lodash remains a dependency. Is this a normal and temporary situation? (with the end goal to remove `lodash` completely?)

Thank you for your attention to these matters. And sorry for creating such an issue, I tried my best to have a nice tone in the message but it still feels like I demand things like an entitled freeloader :/

**Comment by tnrich** [comment]
Hi @NicolasCARPi you make some good points. 

You're right that react and react-dom have been removed as deps. I'd like to avoid adding them as peer-deps since I find peer deps to be somewhat restrictive with the version ranges. They will need to be added alongside ove / ui so that should be added to the docs. 

I think having a single changelog file per each package would be ideal. That said, I'm not quite sure how to set that up for a monorepo.. Any ideas or suggestions would be welcomed. 

lodash should be removed in favor of lodash-es. I'll do that. 

Thank you for letting me know about these issues. Please feel free to make as many tix as you like! Of course I'd always appreciate help fixing things too haha! 

Cheers!

**Comment by NicolasCARPi** [comment]
I'll come back to it in a few weeks probably, whenever I try and update the version in my app, I'll propose some changes to the documentation/changelog at this moment.

Best,
~Nico

**Comment by tnrich** [comment]
@NicolasCARPi can I close this one?

**Comment by NicolasCARPi** [comment]
Yes sure, I'll come back to it if needed. At the moment I didn't update OVE yet.
